### ISSUE TITLE
Prompt string

### ISSUE THREAD

**Issue by ksunden** [ksunden/h5cli#27]
My current leaning:
`[<filename>: <current directory>] > `

so if you were in `foo.h5` and within the `bar` group, it would appear as `[foo.h5: bar] > `

I prefer just the group name (keeps the prompt from growing far to long), not the full path, though perhaps that should be configurable

if in root, shows up as `/`

Not sold on the last character

**Comment by ksunden** [comment]
Prior to loading, shows up as `[None] >`
Thoughts?

**Comment by lphk92** [comment]
I would just go with `[] >` before you have a file loaded, and then just fill in the parenthesis once you have a file.

I like that idea of showing the current directory along with the filename once you load it up though, that's slick.

**Comment by ksunden** [comment]
Thoughts on last character?

**Comment by ksunden** [comment]
I have implemented exactly as shown above, with one slight modification:
it shows up as `[foo.h5: bar/] > `, adding the trailing `/` regardless of whether you are in root or some other directory 

(will be pushing to `issues/27` shortly, is this behavior satisfactory to close the issue?)

**Comment by lphk92** [comment]
I like the `>` for the last character.

One thing though about your current implementation: You should always show the leading `/` (eg. it should be `[foo.h5: /bar/] >`, otherwise this looks good to me.

**Comment by ksunden** [comment]
Commented in #31 , but that would be confusing, I think

if bar is a subgroup of baz, then either we would need to show `/baz/bar/` or just `bar/`,  `/bar/` would be confusing
