### ISSUE TITLE
dtype command

### ISSUE THREAD

**Issue by untzag** [ksunden/h5cli#29]
😊

**Comment by lphk92** [comment]
What exactly would this do? Just show you the dtype of a particular Dataset?

**Comment by untzag** [comment]
Yes, it would just allow inspection of a dataset's dtype.

Now that I think about it I would find all of the following useful:
- dtype
- shape, size, maxshape
- chunks (dataset chunk shape)
- compression (dataset compression algorithm)

If it seems unreasonable to add all of these as separate commands, you might consider displaying them as if they were attributes of the dataset.

**Comment by lphk92** [comment]
I would hesitate to display them as if they  were attributes, to avoid confusing them for actual attributes. I could however see it being useful to have these as individual commands but also have a `describe` command that prints out a summary of all this data.

**Comment by ksunden** [comment]
@untzag What is the difference between shape and size?
Does size mean disk space? Or does it mean number of elements (the shape multiplied together)


I'm thinking `shape` should have either `-f` for flatten or `-n` for number of elements for the latter.

I would suggest `du` for the former

**Comment by ksunden** [comment]
link to #22 and #21
