### ISSUE TITLE
Design of H5Explorer

### ISSUE THREAD

**Issue by lphk92** [ksunden/h5cli#30]
Looking at the remaining backend tickets, as well as what we have so far, I'm realizing that H5Explorer is basically just becoming a really light wrapper on top of the existing h5py File object, with the one extra feature being that it remember the working directory and handle relative and absolute file paths.

I'm thinking it would probably make sense to just implement the `__getitem__` function for H5Explorer (and maybe some extra functions for enforcing that something is a Group or Dataset) and resolve the paths and return you the File object with the appropriate path applied. Then, it's still just a 1-line call from the CLI class, but we won't have to update H5Explorer every time we want to implement a new function.

@ksunden What do you think?

**Comment by ksunden** [comment]
I think I like it, can you give an example of what it would look like for a cli call?

**Comment by lphk92** [comment]
Sure, so like the implementation of rm would just become

```python
del self.explorer[path]
```

or if you wanted to ensure that it was a group you were deleting
```python
del self.explorer.group[path]
```
or something along those lines.

**Comment by ksunden** [comment]
I like it

Slightly off topic: does `del` work in the `rm` sense of actually removing the group/dataset?

**Comment by lphk92** [comment]
I mean it does in-so-far-as HDF5 deletes anything. (still might just be marking the memory chunks as usable and then they just go overwritten with new data)

**Comment by lphk92** [comment]
And cool, I'll get started on this as an actual implementation change then.

Also, I still think we should keep all the navigational stuff (pushd, popd, change_dir) in the explorer implementation since it maintains the directory state.

**Comment by ksunden** [comment]
I agree with pushd/popd

**Comment by ksunden** [comment]
Would this be a good change to make a `development` branch for, that way we could merge the basics, while breaking the front end and fix those as atomic units, while keeping master functional

**Comment by lphk92** [comment]
I agree, I'll create one to use for this.

**Comment by ksunden** [comment]
@lphk92 Any new thoughts on this?

**Comment by lphk92** [comment]
Still think this is probably a design change worth doing, although I haven't had time recently to do it. I should start having a little more time next week that I could start taking a look at this ticket. Alternatively if you wanted to take a crack at it I'd be happy to review :-)
