### ISSUE TITLE
enter directly into cli with file

### ISSUE THREAD

**Issue by untzag** [ksunden/h5cli#36]
I find the enter then `load` step clunky

would be nice to enter into the cli from bash directly using `h5cli myfile.h5`

this would make it easier to quickly jump between files

perhaps I just don't understand the design principles that you're going for

**Comment by ksunden** [comment]
Yeah, that is the plan, I tried to implement that once, but it didn't quite work, need to revisit

**Comment by ksunden** [comment]
You'll notice that the README indicates that you can do this, because I wrote that right before I started working on that feature, but that turned out to be harder to do than I thought, may end up needing to do that parsing in main

**Comment by ksunden** [comment]
I have an initial implementation of this, but it is still throwing an error, that I need to trace

**Comment by ksunden** [comment]
This has been fixed (see PR #41)
