### ISSUE TITLE
su and sudo commands to elevate to write privileges

### ISSUE THREAD

**Issue by ksunden** [ksunden/h5cli#47]
I would lean towards the default being 'a', rather than read only

**Comment by lphk92** [comment]
I see the reasoning for that, as that would likely be the most common use case. However, I feel like philosophically you want to make the ability to delete datasets opt-in instead of available by default.

**Comment by ksunden** [comment]
Would it be appropriate to use `sudo`/`su` to elevate to append permissions? I don't think we need to worry about password protection, but we could even use an attribute of the root which allows for storage of a (hashed, because why not) password. This is more of a fun little aside, rather than real useful protection, as file permissions will still be in effect, and to edit hdf5 files as root would require sudo on the entry call, not within.

I'd like to make it as easy and natural for bash users to interact with their HDF5 files. I think requiring users to elevate permissions, but making it easy to do so accomplishes those goals.

@untzag how do you feel about this proposal?

**Comment by ksunden** [comment]
`su` in this case would overtake the need for #43, as the purpose of that was largely to reopen and allow for write permission

We could even change up the prompt string for "root" mode

**Comment by lphk92** [comment]
I like the idea of using `sudo`/`su` for opening in append mode (in addition to potentially having a flag in the `load` command?)
