### ISSUE TITLE
`chunks` command or flag on shape

### ISSUE THREAD

**Issue by ksunden** [ksunden/h5cli#52]
I'm leaning towards `-c`/`--chunks` on the `shape` command

From comments in #29

**Comment by lphk92** [comment]
Is this going to just be the shape of the chunks, or also show information about how many chunks a particular dataset is using? If the latter, then I think it makes more sense to have a separate command for `chunks`

**Comment by ksunden** [comment]
@untzag, as the original proposer of such functionality, what did you have in mind?

**Comment by ksunden** [comment]
http://docs.h5py.org/en/latest/high/dataset.html#Dataset.chunks
